#!/usr/bin/env node
/**
 * Build script for London Field Guide — two independent steps.
 *
 * Step 1 (always runs, zero dependencies):
 *   Writes config.js with MAPBOX_TOKEN + ANTHROPIC_KEY flag from
 *   Vercel environment variables.
 *
 * Step 2 (optional, requires esbuild):
 *   Compiles the inline JSX to plain JS so the in-browser Babel
 *   transformer is no longer needed in production.
 *   Wrapped in try/catch — if esbuild is unavailable the app still
 *   works perfectly, just with the Babel console warning.
 */
const fs = require('fs');
const path = require('path');

// ── Step 1: Write config.js (always succeeds) ─────────────────────────────────
const token  = process.env.MAPBOX_TOKEN    || '';
const hasKey = !!process.env.ANTHROPIC_KEY;

fs.writeFileSync(
  path.join(__dirname, 'config.js'),
  `/* Generated by Vercel build — do not edit */\n` +
  `window.LONDON_GUIDE_CONFIG={mapboxToken:${JSON.stringify(token)},hasAnthropicKey:${hasKey}};\n`
);

console.log('[build] Step 1 complete: config.js written');
console.log('[build]   MAPBOX_TOKEN  :', token ? `present (${token.slice(0,8)}...)` : 'not set');
console.log('[build]   ANTHROPIC_KEY :', hasKey ? 'present' : 'not set');

// ── Step 2: Compile JSX with esbuild (optional) ───────────────────────────────
try {
  const { transformSync } = require('esbuild');
  const htmlPath = path.join(__dirname, 'index.html');
  const html     = fs.readFileSync(htmlPath, 'utf8');

  const babelRe = /<script type="text\/babel" data-presets="react">([\s\S]*?)<\/script>/;
  const match   = html.match(babelRe);

  if (!match) {
    console.log('[build] Step 2: no Babel block found — JSX already compiled.');
  } else {
    const { code, warnings } = transformSync(match[1], {
      loader:            'jsx',
      jsxFactory:        'React.createElement',
      jsxFragment:       'React.Fragment',
      target:            ['chrome90', 'firefox90', 'safari14', 'edge90'],
      minifyWhitespace:  true,
      minifySyntax:      true,
      minifyIdentifiers: false,
    });

    if (warnings.length) warnings.forEach(w => console.warn('[build] esbuild warning:', w.text));

    const compiled = html
      .replace(/\n?<script src="https:\/\/unpkg\.com\/@babel\/standalone[^"]*"><\/script>/, '')
      .replace(babelRe, `<script>\n${code}\n</script>`);

    fs.writeFileSync(htmlPath, compiled);
    console.log(`[build] Step 2 complete: JSX compiled (${(match[1].length/1024).toFixed(1)} KB → ${(code.length/1024).toFixed(1)} KB)`);
    console.log('[build]   Babel transformer removed from page.');
  }
} catch (err) {
  console.log('[build] Step 2 skipped:', err.message);
  console.log('[build]   App will use in-browser Babel (warning in console, no functional impact).');
}

console.log('\n[build] Done.');
