#!/usr/bin/env node
/**
 * Build script — zero dependencies, uses only Node.js built-in fs.
 * Reads MAPBOX_TOKEN and ANTHROPIC_KEY from Vercel environment variables
 * and writes them into config.js so the page loads the map immediately.
 *
 * The Mapbox public token (pk.*) is safe to embed in a static file —
 * it is a client-side credential by design.
 *
 * The Anthropic key is NEVER written to config.js. Only a boolean flag
 * (hasAnthropicKey) is embedded. The actual key stays server-side in
 * api/agent.js which proxies requests securely.
 */
const fs = require('fs');

const token  = process.env.MAPBOX_TOKEN    || '';
const hasKey = !!process.env.ANTHROPIC_KEY;

fs.writeFileSync(
  'config.js',
  `/* Generated by Vercel build — do not edit */\n` +
  `window.LONDON_GUIDE_CONFIG={mapboxToken:${JSON.stringify(token)},hasAnthropicKey:${hasKey}};\n`
);

console.log('[build] config.js written');
console.log('[build] MAPBOX_TOKEN  :', token ? `set (${token.slice(0, 8)}...)` : 'NOT SET — users will enter manually');
console.log('[build] ANTHROPIC_KEY :', hasKey ? 'set' : 'NOT SET — Update all will need user key');
